Fix syntax error with CREATE MATERIALIZED VIEW
Allow DISTRIBUTED BY when using the CREATE MATERIALIZED VIEW
IF NOT EXISTS SYNTAX.

Resolves error:

CREATE MATERIALIZED VIEW IF NOT EXISTS mvtest AS SELECT * FROM mvtest_tvvmv DISTRIBUTED RANDOMLY;
ERROR:  syntax error at or near "DISTRIBUTED"

Update matview regress tests to test `IF NOT EXISTS` with `DISTRIBUTED BY`

Authored-by: Brent Doil <bdoil@vmware.com>