ao/co: Address index build scan FIXME
By addressing the FIXME, this commit addresses 2 main issues:

* We have to let the index AM know if a tuple is deleted.
Failing to do the above can have consequences. There are some index AMs
that don't really do anything with this information (like bitmap
indexes). However, AMs like B-Tree rely on this information (specially
for uniqueness conflicts during unique index builds). Below is an
example of how things can go wrong if we bubble up incorrect visibility
information:

CREATE TABLE bar(i int) USING ao_row;
INSERT INTO bar VALUES(1),(1);
DELETE FROM bar WHERE i = 1;
CREATE UNIQUE INDEX ON bar(i);
ERROR:  could not create unique index "bar_i_idx"  (seg1 ...)
DETAIL:  Key (i)=(1) is duplicated.

* If a tuple is deleted, we shouldn't add it to the table's reltuples on
the segment. We were adding it regardless, leading to an incorrect value
of reltuples.

This commit introduces a visimap check to the table AM API for index
builds, to weed out deleted tuples, such that the visibility info and
reltuples calculation is correct.

Further, it adds coverage for the reltuples calculation for general
index builds and coverage for unique index builds.