[7X] Fix psycopg2 encoding issue (#16408)
psycopg2's `getquoted()` API returns `latin-1` encoded binary string by default which is causing unexpected failures to some gpMgmt tools including gpload, analyzedb, minirepro. This patch helps fix it by teaching psycopg2's `QuotedString` adapter use `utf-8` encoding.

Reproducing steps for `analyzedb`:

Create a table with special name.

```sql
postgres=# create table spiegelungssätze(i int);
```

Run `analyzedb` against the postgres db.

```bash
$ analyzedb -d postgres
```

Backtrace:

```
➜ analyzedb -d postgres
20230910:21:51:11:689552 analyzedb:laptop:v-[INFO]:-Starting analyzedb with args: -d postgres
20230910:21:51:11:689552 analyzedb:laptop:v-[INFO]:-Getting and verifying input tables...
20230910:21:51:11:689552 analyzedb:laptop:v-[INFO]:-Checking for tables with stale stats...
20230910:21:51:11:689552 analyzedb:laptop:v-[ERROR]:-'utf-8' codec can't decode byte 0xe4 in position 21: invalid continuation byte
Traceback (most recent call last):
  File "/home/v/.local/gpdb7/bin/analyzedb", line 376, in execute
    heap_partitions = get_heap_tables_set(self.conn, input_tables_set)  # set((schema1,table1), ...])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v/.local/gpdb7/bin/analyzedb", line 1004, in get_heap_tables_set
    oid_str = get_oid_str(input_tables_set)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v/.local/gpdb7/bin/analyzedb", line 976, in get_oid_str
    return ','.join(map((lambda x: regclass_schema_tbl(x[0], x[1])), table_list))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v/.local/gpdb7/bin/analyzedb", line 976, in <lambda>
    return ','.join(map((lambda x: regclass_schema_tbl(x[0], x[1])), table_list))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v/.local/gpdb7/bin/analyzedb", line 984, in regclass_schema_tbl
    return "to_regclass('%s')" % (escape_string(schema_tbl))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v/.local/gpdb7/lib/python/gppylib/utils.py", line 515, in escape_string
    return adapted.getquoted().decode()[1:-1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 21: invalid continuation byte
20230910:21:51:11:689552 analyzedb:laptop:v-[CRITICAL]:-analyzedb failed. (Reason=''utf-8' codec can't decode byte 0xe4 in position 21: invalid continuation byte') exiting...
```