Enable `Copy partitioned_table TO file` for better performence (#15191)
PostgreSQL does not support copying partitioned tables to files. Refer to: https://www.postgresql.org/docs/12/sql-copy.html

> COPY TO can only be used with plain tables, not views, and does not copy rows from child tables or child partitions.
> For example, COPY table TO copies the same rows as SELECT * FROM ONLY table. The syntax COPY (SELECT * FROM table)
> TO ... can be used to dump all of the rows in an inheritance hierarchy, partitioned table, or view.

```
postgres=# copy rank to '/tmp/test1';
ERROR:  cannot copy from partitioned table "rank"
HINT:  Try the COPY (SELECT ...) TO variant.
```
In GPDB 7, partitioning was replaced with an upstream implementation. To ensure forward compatibility,
`COPY partitioned_table TO file` is converted to `COPY (SELECT * FROM partitioned_table) TO file`.

---

When executing these two statements separately in GPDB 6, we can see that the performance of
`COPY (SELECT * FROM partitioned_table) TO file` is much worse.

```
postgres=# SELECT COUNT(*) FROM rank;
   count
-----------
 100000000
(1 row)
postgres=# \timing
Timing is on.
postgres=# COPY rank TO '/tmp/test1';
COPY 100000000
Time: 34176.985 ms
postgres=# COPY (SELECT * FROM rank) TO '/tmp/test2';
COPY 100000000
Time: 128893.366 ms

```

The reason for this performance difference is that `COPY partitioned_table TO file` converts tuples
to text on each QE and sends them to QD before writing to the file. On the other hand,
`COPY (SELECT * FROM partitioned_table) TO file` requires executing a query to gather all tuples to
QD before converting them to text and writing to the file. In other words,
`COPY partitioned_table TO file` performs tuple-to-text conversion in parallel.

To improve performance, this commit re-implements COPY partitioned_table TO file by traversing all
sub-tables on QE. If there are external tables with partitions, users need to explicitly declare
`IGNORE EXTERNAL PARTITIONS`, otherwise an error will be reported and the user will be prompted to
modify the command to COPY (SELECT * FROM partitioned_table) TO file(consistent with the behavior of GPDB6).

Related issue: https://github.com/greenplum-db/gpdb/issues/14948.