Remove fixme in nodeModifyTable.c. (#17119)
Before this PR, when merging 9.6, this part of code was commented
by the commit https://github.com/greenplum-db/gpdb-postgres-merge/commit/2a864ff1421a631be1ebd2fb68f93cdfb8df09a4.

The test case will report error because the tle->expr is var not const.

test=# create table base_tbl (a int4, b int4) distributed by (a);
CREATE TABLE
test=# insert into base_tbl select g, g from generate_series(1, 5) g;
INSERT 0 5
test=# explain (costs off) update base_tbl set a=a+1;
                          QUERY PLAN
---------------------------------------------------------------
 Update on base_tbl
   ->  Explicit Redistribute Motion 3:3  (slice1; segments: 3)
         ->  Split
               ->  Seq Scan on base_tbl
 Optimizer: Postgres query optimizer
(5 rows)

test=# alter table base_tbl drop column b;
ALTER TABLE
test=# explain (costs off) update base_tbl set a=a+1;
ERROR:  table row type and query-specified row type do not match
DETAIL:  Query provides a value for a dropped column at ordinal position 2.

But on the latest version, inside the set_dummy_tlist_references(), if it's const,
it will skip makeVar() for the dropped column.

We have merged the commit da8f3eb to fix the problem. So remove the fixme.