Fix windows clients compilation of libpgcommon
The commit https://github.com/greenplum-db/gpdb/commit/ab12230fa11574bf2e7470242489864fe8a63c1b
added some WIN32 ifdefs to fix fe-connect compilation errors.

The commit https://github.com/greenplum-db/gpdb/commit/5d3dc2e81f272396281eddc082bd998ab96fd0da
allows hashfn.c to be compiled into both frontend and backend code but
broke the win32 clients compilation with

`src\include\utils\elog.h(86): fatal error C1083: Cannot open include
file: 'pthread-win32.h': No such file or directory (compiling source
file src/common/hashfn.c)`

We carry a dependency on pthread_win32.h in elog.h, which causes
compilation errors when building Windows clients (as elog.h is included by
postgres.h). So use postgres_fe.h instead for this case.

Authored-by: Brent Doil <bdoil@vmware.com>