pg_upgrade: Remove unnecessary line type check
The line data type is not implemented in GPDB5 (PG 8.3), no
values can be inserted into a line datatype.

postgres=# \d foo
      Table "public.foo"
 Column |  Type   | Modifiers
--------+---------+-----------
 a      | integer |
 b      | line    |
Distributed by: (a)

postgres=# insert into foo values (1, '{1,4,9}');
ERROR:  type "line" not yet implemented
LINE 1: insert into foo values (1, '{1,4,9}');

The line type was revived for PG 9.4 in commit 261c7d4.
This means the check old_9_3_check_for_line_data_type_usage
is not useful because the on-disk representation only changed
for GPDB6 (PG 9.4) and is compatible with GPDB7 (PG12).