Fix flaky test fts_errors with nondeterministic error in FETCH
This test is flaky in terms of where error will be thrown during a
FETCH cursor transaction when some original primary segments are down.
For example:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/expected/fts_errors_1.out	2022-03-09 10:00:32.786358101 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/results/fts_errors.out	2022-03-09 10:00:32.802359582 +0000
@@ -140,13 +153,11 @@
 -- session 3: in transaction and has a cursor, cann't update
 --            cdb_component_dbs, following query should fail
 3:FETCH ALL FROM c1;
- c1 | c2
-----+----
-(0 rows)
-3:END;
 ERROR: server closed the connection unexpectedly
 	This probably means the server terminated abnormally
 	before or while processing the request.
+3:END;
+END
```

The test expects no error during FETCH but an error in the END statement,
since QD should have enough data already bufferred at sockets for it
to read and doesn't need to reach out to QEs (the table has size 0).
However, sometimes when the interconnect is proxy, this is not true and
when QD tries to check the status of QEs an error will be thrown.
Fix this by removing the FETCH and let it always error out during END.