Ensure that a COPY child never runs atexit callbacks
If a COPY .. PROGRAM child runs exit() before it is re-imaged with
execl() inside popen_with_stderr(), it will run the parent's atexit
callbacks (in addition to the parent) -> effectively we will have both
the parent and child clean up the same PGPROC object, as they both will
call ProcKill().

On an asserts build, various shmem sanity checks will fail. Depending on
the state of locks in the backend on a non-asserts build, the COPY
parent may cause a PANIC with "failed to re-find shared lock|proclock
object".

Alternatively, it might not and a subsequent backend will grab the
"double-killed" PGPROC (pointing to itself as a result of the double
ProcKill()) and then blow up in OwnLatch:
"latch already owned by pid"

Appendix: Why not just use upstream logic such as OpenPipeStream() or
ClosePipeStream()? Because this is what we get with our current
implementation:

CREATE TABLE COPY_FROM_PROGRAM_ERROR(a int);

In PG:
postgres=# copy copy_from_program_error from program 'cat foo';
ERROR:  program "cat foo" failed
DETAIL:  child process exited with exit code 1

But in GPDB:
postgres=# copy copy_from_program_error from program 'cat foo';
ERROR:  command error message: cat: foo: No such file or directory

Co-authored-by: Huansong Fu <fuhuansong@gmail.com>
Reviewed-by: Brent Doil <bdoil@vmware.com>
Reviewed-by: Jimmy Yih <jyih@vmware.com>