Support VACUUM on AO/CO tables with unique indexes
AO lazy VACUUM is different from heap vacuum in the sense that ctids of
data tuples change (and the index tuples need to be updated as a
consequence). It leverages the scan and insert code to scan live tuples
from each segfile and to move (insert) them in a target segfile. The
previous commit that added support for INSERT on AO tables with unique
indexes, is sufficient to entertain uniqueness checks running
concurrently with vacuum. That commit did not introduce the placeholder
row mechanism to the vacuum code however, as it is not necessary for
correctness. This is because the old index entries will still point to
the segment being compacted. This will be the case up until the index
entries are bulk deleted, but by then the new index entries along with
new block directory rows would already have been written and would be
able to answer uniqueness checks.

This commit has 2 main contributions:

1. Concurrency coverage for uniqueness checks running parallel with
VACUUM, to enforce that the mechanism added in the prior INSERT commit is
sufficient.

2. Running uniqueness checks in the backend running AO VACUUM results in
spurious uniqueness conflicts. Live tuples being moved (inserted into
a new segfile) report a unique constraint violation against themselves.

Example:

test=# SET debug_appendonly_print_blockdirectory TO ON;
SET
test=# create table bar(i int unique) using ao_row;
CREATE TABLE
test=# insert into bar select generate_series(1, 10);
INSERT 0 10
test=# delete from bar where i = 1;
DELETE 1
test=# vacuum full verbose bar;
INFO:  vacuuming "public.bar"
INFO:  compacting "public.bar"
LOG:  For segno = 0, rownum = 2, tid returned: (0,2) tuple (xmin, xmax) = (940, 0), snaptype = 4
ERROR:  duplicate key value violates unique constraint "bar_i_key"
DETAIL:  Key (i)=(2) already exists.

The above reports a conflict while trying to move tuple with i = 2.

Remedy this by adding the capability to bypass uniqueness checks when
inserting index tuples in ExecInsertIndexTuples(). This is done by a new
EState member: gp_bypass_unique_check, which AO lazy VACUUM can set.

Co-authored-by: Ashwin Agrawal <aashwin@vmware.com>